org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
kotlin.code.style=official
android.useAndroidX=true
APP_VERSION_NAME=0.0.3-snapshot.4
APP_VERSION_CODE=7
android.nonTransitiveRClass=true
UBUNTU_MAVEN_GROUP=io.github.meteor149
UBUNTU_RUNTIME_VERSION=0.3.0-SNAPSHOT
UBUNTU_IMAGE_VERSION=24.04-1

# Release dependencies are resolved from Maven Central by default.
USE_LOCAL_UBUNTU_LIBRARIES=false
USE_LOCAL_UBUNTU_MAVEN=false
